apiVersion: v1
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJjbG91ZC5vcGVuc2hpZnQuY29tIjogewogICAgICAiYXV0aCI6ICJibUZ0WlRwd1lYTnpDZz09IiwKICAgICAgImVtYWlsIjogImFrcnpvc0ByaC5jb20iCiAgICB9LAogICAgInF1YXkuaW8iOiB7CiAgICAgICJhdXRoIjogImJtRnRaVHB3WVhOekNnPT0iLAogICAgICAiZW1haWwiOiAiYWtyem9zQHJoLmNvbSIKICAgIH0sCiAgICAicXVheS5pbzo0NDMiOiB7CiAgICAgICJhdXRoIjogImJtRnRaVHB3WVhOekNnPT0iLAogICAgICAiZW1haWwiOiAiYWtyem9zQHJoLmNvbSIKICAgIH0sCiAgICAicmVnaXN0cnkuY2kub3BlbnNoaWZ0Lm9yZyI6IHsKICAgICAgImF1dGgiOiAiYm1GdFpUcHdZWE56Q2c9PSIKICAgIH0sCiAgICAicmVnaXN0cnkuY29ubmVjdC5yZWRoYXQuY29tIjogewogICAgICAiYXV0aCI6ICJibUZ0WlRwd1lYTnpDZz09IiwKICAgICAgImVtYWlsIjogImFrcnpvc0ByaC5jb20iCiAgICB9LAogICAgInJlZ2lzdHJ5LnJlZGhhdC5pbyI6IHsKICAgICAgImF1dGgiOiAiYm1GdFpUcHdZWE56Q2c9PSIsCiAgICAgICJlbWFpbCI6ICJha3J6b3NAcmguY29tIgogICAgfQogIH0KfQo=
kind: Secret
metadata:
  name: assisted-deployment-pull-secret
  namespace: sno00001
type: kubernetes.io/dockerconfigjson
